### ISSUE TITLE
Working  with partitions

### ISSUE THREAD

**Issue by remche** [intake/intake-parquet#30]
We are working with a multiple files catalog, eg:

```yaml
plugins:
  source:
    - module: intake_parquet
sources:
  test:
    description: Short example parquet data
    driver: parquet
    args:
      urlpath: 
        - s3://bucket/path/file.parquet
        - s3://bucket/path/file2.parquet
        - s3://bucket/path/file3.parquet
      storage_options:
        anon: True
        client_kwargs:
          endpoint_url: https://example.com
```

1.  With only two entries, `discover()` is fine, we can `read_partition(0)` and `read_partition(1)`, but a full `read()` fails with `ValueError: storage_options passed with buffer, or non-supported URL`, probably because `ParquetSource.read()`does not handle array in `url_path`.
2. With more that 2 entries, `discover()` fails with a `[KeyError](https://github.com/intake/intake-parquet/files/13673671/traceback.txt).

Thanks for maintaining this intake plugin !
